### ISSUE TITLE
"Increase buffer_size" and not sending message

### ISSUE THREAD

**Issue by amunhoz** [Squadrick/shadesmar#45]
I'm trying to create a server/client system with Shadesmar, using topics to communicate with specific clients.
After the server receive the message, it responds and then i get this problem.
Both, server and client are running on the same instance. Only two messages was exchanged, so, i dont think i could be a memory problem.
Other specs:
- i'm using multithread.
- the copier and publisher are created at a global map
- tried to create a new instance of copier and publisher to send a message back, same problem.

any ideas?

other questions:
- Can i use the same 'DefaultCopier' with multiple publishers/topics?
- Can i use the same 'DefaultCopier' to publish and subscribe?

**Comment by Squadrick** [comment]
Pubsub should ideally be used for one-way communication, for server/client interactions it's better to use the RPC mechanism (which is currently broken, I'll try to get it up and running soon #20).

Do you have the code snippet that causes this? It'll make it simpler to debug.

I have a couple more questions:
1. Are you using a regular `Publisher`/`Subscriber` or the Serialized variants?
2. What is the size of messages being sent over the topic?

Can you try changing your topic name and re-run the app? If this persists, you'll need to clone and build shadesmar. There's a simple executable called [`flush_tmp.cpp`](https://github.com/Squadrick/shadesmar/blob/master/src/flush_tmp.cpp) that cleans up any allocated shader memory from previous runs. 

I pushed a fix to this problem a while back (#42), but it's possible that I didn't resolve it entirely.

> * Can i use the same 'DefaultCopier' with multiple publishers/topics?
> * Can i use the same 'DefaultCopier' to publish and subscribe?

`DefaultCopier` is stateless so both these things should be possible.

**Comment by egoist-sx** [comment]
@Squadrick  Hey, thank you for your good work. I still encounter same problem. After some inspection, it seems that circular buffer is not working. In Allocator class, free_index is not modified and it's always zero, and in get_free_memory, it only go through first if logic. In this case, "get_free_memory" returns decreasing value.
